services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=bugdb
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - bug-report-network

  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - bug-report-network
    links:
      - mysql

networks:
  bug-report-network:
    name: bug-report-network
    driver: bridge